### ISSUE TITLE
Swipe-Gestures fail when PagerTabStripView is embedded in a SplitView

### ISSUE THREAD

**Issue by detlevwiese** [xmartlabs/PagerTabStripView#79]
Great project! Thank you!

I have a setup where the PagerTabStripView is embedded in a SplitView with two Subviews: the typical master and detail layout, the PagerTabStripView is my detail view. 

Swiping between tabs works perfectly whenever the PagerTabStripView is the only view (master side hidden):  
- on iPads in portrait orientation
- on iPhones 

It does not work, when the master und detail views are both visible side by side (iPad landscape). The swipe gesture itself works, but it does not allow me to turn a page. 

I have tried to move the PagerTabStripView to the master side: swipe gestures work on the master side! So the only case where it does not work is the side by side case with the PagerTabStripView on the detail side.

XCode 12.0, iOS 15.2, PagerTabStripView 3.1.1

**Comment by mtnbarreto** [comment]
Have you tried disabling gestures in the split view or the pagerView?

**Comment by mlorenze** [comment]
On master branch is implemented a solution for this behavior (**available for iOS 16+**).
In Readme is available this documentation to work with that:

The user can also configure if the swipe action is enable or not (the swipe is based on a drag gesture) and setup what edges have the gesture disabled.

Params:
- `swipeGestureEnabled`: swipe is enabled or not (default is true).
- `edgeSwipeGestureDisabled`: is an HorizontalContainerEdge (OptionSet) value where the array could have this options: .left, .right, .both or be empty (default is an empty array).

What is the importance to have this parameter?
Regarding the next PagerTabStripView example in `MyPagerView2`: if the pager is in the first page and the user try to swipe to the left, is possible to catch a parent view gesture (where this pager is embebbed) instead of catching the actual pager swipe gesture because it is disabled with the `edgeSwipeGestureDisabled` paramenter.

```swift
struct MyPagerView2: View {

    @State var selection = 1

    var body: some View {
        PagerTabStripView(swipeGestureEnabled: .constant(true),	
			  edgeSwipeGestureDisabled: .constant([.left]),
			  selection: $selection) {
            MyFirstView()
                .pagerTabItem(tag: 1) {
                    TitleNavBarItem(title: "Tab 1")
                }
            ...
            ..
            .
        }
    }
}
```
